/* tslint:disable */
/* eslint-disable */
/**
 * Klokasale
 * Klokasale backend server api.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CommonErrorResponse
 */
export interface CommonErrorResponse {
    /**
     * 
     * @type {CommonErrorResponseError}
     * @memberof CommonErrorResponse
     */
    'error'?: CommonErrorResponseError;
}
/**
 * 
 * @export
 * @interface CommonErrorResponseError
 */
export interface CommonErrorResponseError {
    /**
     * can be custom error if necessary
     * @type {number}
     * @memberof CommonErrorResponseError
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonErrorResponseError
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface CommonSuccessResponse
 */
export interface CommonSuccessResponse {
    /**
     * 
     * @type {object}
     * @memberof CommonSuccessResponse
     */
    'data'?: object;
}
/**
 * 
 * @export
 * @interface UserUserLoginReq
 */
export interface UserUserLoginReq {
    /**
     * 
     * @type {string}
     * @memberof UserUserLoginReq
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof UserUserLoginReq
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface UserUserLoginResp
 */
export interface UserUserLoginResp {
    /**
     * 
     * @type {string}
     * @memberof UserUserLoginResp
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface V1UsersLoginPost200Response
 */
export interface V1UsersLoginPost200Response {
    /**
     * 
     * @type {UserUserLoginResp}
     * @memberof V1UsersLoginPost200Response
     */
    'data'?: UserUserLoginResp;
}

/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary User Login
         * @param {UserUserLoginReq} loginRequest Login Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UsersLoginPost: async (loginRequest: UserUserLoginReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('v1UsersLoginPost', 'loginRequest', loginRequest)
            const localVarPath = `/v1/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary User Login
         * @param {UserUserLoginReq} loginRequest Login Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1UsersLoginPost(loginRequest: UserUserLoginReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1UsersLoginPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1UsersLoginPost(loginRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['UsersApi.v1UsersLoginPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary User Login
         * @param {UserUserLoginReq} loginRequest Login Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UsersLoginPost(loginRequest: UserUserLoginReq, options?: any): AxiosPromise<V1UsersLoginPost200Response> {
            return localVarFp.v1UsersLoginPost(loginRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary User Login
     * @param {UserUserLoginReq} loginRequest Login Request Body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public v1UsersLoginPost(loginRequest: UserUserLoginReq, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).v1UsersLoginPost(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



